commonAnnotations:
  circleci.com/pipeline-id: ${CIRCLE_PIPELINE_ID}
  circleci.com/workflow-id: ${CIRCLE_WORKFLOW_ID}
  circleci.com/project-id: ${CIRCLE_PROJECT_ID}
  circleci.com/job-number: "${CIRCLE_BUILD_NUM}"
commonLabels:
  app: frontend
  version: ${APP_VERSION}
resources:
- frontend.yaml
patchesStrategicMerge:
- template_patch.yaml
- virtual_service_region.yaml
